// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Powertech.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace Powertech.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

<<<<<<< Updated upstream
=======
            modelBuilder.Entity("Powertech.Platform.Fleet.Domain.Model.Aggregates.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("longtext")
                        .HasColumnName("departure_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<string>("ServiceDays")
                        .HasColumnType("longtext")
                        .HasColumnName("service_days");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("p_k_routes");

                    b.ToTable("routes");
                });

            modelBuilder.Entity("Powertech.Platform.Iam.Domain.Model.Aggregates.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Powertech.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Powertech.Platform.Notifications.Domain.Model.Aggregates.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("DeliveryState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("delivery_state");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("message");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Powertech.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Entities.VehicleCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("model");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("plate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_vehicles");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Powertech.Platform.Stakeholder.Domain.Model.Aggregates.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_parents");

                    b.ToTable("parents", (string)null);
                });

            modelBuilder.Entity("Powertech.Platform.Stakeholder.Domain.Model.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("available");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("license_number");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_drivers");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("Powertech.Platform.Stakeholder.Domain.Model.Entities.StudentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ChildIds")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("child_ids");

                    b.Property<bool>("IsFinalizedValue")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_finalized_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("p_k_student_groups");

                    b.ToTable("student_groups", (string)null);
                });

            modelBuilder.Entity("Powertech.Platform.Subscription.Domain.Model.Aggregates.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("DriverQuota")
                        .HasColumnType("int")
                        .HasColumnName("driver_quota");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("RouteQuota")
                        .HasColumnType("int")
                        .HasColumnName("route_quota");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("p_k_plans");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("Powertech.Platform.Subscription.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("i_x_subscriptions_plan_id");

                    b.ToTable("subscriptions", (string)null);
                });

>>>>>>> Stashed changes
            modelBuilder.Entity("Powertech.Platform.Trip.Domain.Model.Aggregates.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)")
                        .HasColumnName("driver_id");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("route_id");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("p_k_trips");

                    b.ToTable("trips");
                });

            modelBuilder.Entity("Powertech.Platform.Trip.Domain.Model.Aggregates.Trip", b =>
                {
                    b.OwnsMany("Powertech.Platform.Trip.Domain.Model.Entities.Attendance", "Attendances", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("BoardedAt")
                                .HasColumnType("datetime")
                                .HasColumnName("boarded_at");

                            b1.Property<string>("BoardingState")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("boarding_state");

                            b1.Property<Guid>("ChildId")
                                .HasColumnType("char(36)")
                                .HasColumnName("child_id");

                            b1.Property<Guid>("TripId")
                                .HasColumnType("char(36)")
                                .HasColumnName("trip_id");

                            b1.HasKey("Id")
                                .HasName("p_k_attendances");

                            b1.HasIndex("TripId")
                                .HasDatabaseName("i_x_attendances_trip_id");

                            b1.ToTable("attendances");

                            b1.WithOwner()
                                .HasForeignKey("TripId")
                                .HasConstraintName("f_k_attendances_trips_trip_id");
                        });

                    b.OwnsMany("Powertech.Platform.Trip.Domain.Model.Entities.Incident", "Incidents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("description");

                            b1.Property<DateTimeOffset>("ReportedAt")
                                .HasColumnType("datetime")
                                .HasColumnName("reported_at");

                            b1.Property<Guid>("TripId")
                                .HasColumnType("char(36)")
                                .HasColumnName("trip_id");

                            b1.HasKey("Id")
                                .HasName("p_k_incidents");

                            b1.HasIndex("TripId")
                                .HasDatabaseName("i_x_incidents_trip_id");

                            b1.ToTable("incidents");

                            b1.WithOwner()
                                .HasForeignKey("TripId")
                                .HasConstraintName("f_k_incidents_trips_trip_id");
                        });

                    b.Navigation("Attendances");

                    b.Navigation("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
